sonar.projectKey=grizzlyt26
sonar.organization=Kamogelo Mafuna

sonar.sources=client/src,server/src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.test.jsx

sonar.javascript.lcov.reportPaths=client/coverage/lcov.info,server/coverage/lcov.info
sonar.securityHotspots.enabled=true